In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
stud =pd.read_csv("/content/student-data.csv")

In [3]:
stud.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes


In [4]:
stud.shape

(395, 31)

In [5]:
stud.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'passed'],
      dtype='object')

In [6]:
stud.isna().sum()

,0
school,0
sex,0
age,0
address,0
famsize,0
Pstatus,0
Medu,0
Fedu,0
Mjob,0
Fjob,0


In [7]:
stud.nunique()

,0
school,2
sex,2
age,8
address,2
famsize,2
Pstatus,2
Medu,5
Fedu,5
Mjob,5
Fjob,5


In [8]:
for column in stud.columns:
  print(column,':',stud[column].unique(),'\n')

school : ['GP' 'MS'] 

sex : ['F' 'M'] 

age : [18 17 15 16 19 22 20 21] 

address : ['U' 'R'] 

famsize : ['GT3' 'LE3'] 

Pstatus : ['A' 'T'] 

Medu : [4 1 3 2 0] 

Fedu : [4 1 2 3 0] 

Mjob : ['at_home' 'health' 'other' 'services' 'teacher'] 

Fjob : ['teacher' 'other' 'services' 'health' 'at_home'] 

reason : ['course' 'other' 'home' 'reputation'] 

guardian : ['mother' 'father' 'other'] 

traveltime : [2 1 3 4] 

studytime : [2 3 1 4] 

failures : [0 3 2 1] 

schoolsup : ['yes' 'no'] 

famsup : ['no' 'yes'] 

paid : ['no' 'yes'] 

activities : ['no' 'yes'] 

nursery : ['yes' 'no'] 

higher : ['yes' 'no'] 

internet : ['no' 'yes'] 

romantic : ['no' 'yes'] 

famrel : [4 5 3 1 2] 

freetime : [3 2 4 1 5] 

goout : [4 3 2 1 5] 

Dalc : [1 2 5 3 4] 

Walc : [1 3 2 4 5] 

health : [3 5 1 2 4] 

absences : [ 6  4 10  2  0 16 14  7  8 25 12 54 18 26 20 56 24 28  5 13 15 22  3 21
  1 75 30 19  9 11 38 40 23 17] 

passed : ['no' 'yes'] 



In [9]:
stud.dtypes

,0
school,object
sex,object
age,int64
address,object
famsize,object
Pstatus,object
Medu,int64
Fedu,int64
Mjob,object
Fjob,object


In [10]:
# one hot encoding

In [11]:
cat_cols = stud.select_dtypes(include =['object'])

In [12]:
cat_cols

,school,sex,address,famsize,Pstatus,Mjob,Fjob,reason,guardian,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,passed
0,GP,F,U,GT3,A,at_home,teacher,course,mother,yes,no,no,no,yes,yes,no,no,no
1,GP,F,U,GT3,T,at_home,other,course,father,no,yes,no,no,no,yes,yes,no,no
2,GP,F,U,LE3,T,at_home,other,other,mother,yes,no,yes,no,yes,yes,yes,no,yes
3,GP,F,U,GT3,T,health,services,home,mother,no,yes,yes,yes,yes,yes,yes,yes,yes
4,GP,F,U,GT3,T,other,other,home,father,no,yes,yes,no,yes,yes,no,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,U,LE3,A,services,services,course,other,no,yes,yes,no,yes,yes,no,no,no
391,MS,M,U,LE3,T,services,services,course,mother,no,no,no,no,no,yes,yes,no,yes
392,MS,M,R,GT3,T,other,other,course,other,no,no,no,no,no,yes,no,no,no
393,MS,M,R,LE3,T,services,other,course,mother,no,no,no,no,no,yes,yes,no,yes


In [13]:
y = stud['passed'].reset_index(drop=True)  # dependend featur and target column
x = stud.drop("passed",axis =1).reset_index(drop=True)

In [14]:
x

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,yes,no,no,4,3,4,1,1,3,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,yes,no,5,3,3,1,1,3,4
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,yes,no,4,3,2,2,3,3,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,yes,3,2,2,1,1,5,2
4,GP,F,16,U,GT3,T,3,3,other,other,...,yes,no,no,4,3,2,1,2,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,yes,no,no,5,5,4,4,5,4,11
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,yes,no,2,4,5,3,4,2,3
392,MS,M,21,R,GT3,T,1,1,other,other,...,yes,no,no,5,5,3,3,3,3,3
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,yes,no,4,4,1,3,4,5,0


In [15]:
y

,passed
0,no
1,no
2,yes
3,yes
4,yes
...,...
390,no
391,yes
392,no
393,yes


In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y = pd.DataFrame(y,columns = ['passed'])


In [17]:
y

,passed
0,0
1,0
2,1
3,1
4,1
...,...
390,0
391,1
392,0
393,1


In [18]:
#Label encoding from x
encoder1 = LabelEncoder()
x['schoolsup'] = encoder1.fit_transform(x['schoolsup'])
x['famsup'] = encoder1.fit_transform(x['famsup'])
x['paid'] = encoder1.fit_transform(x['paid'])
x['activities'] = encoder1.fit_transform(x['activities'])
x['nursery'] = encoder1.fit_transform(x['nursery'])
x['higher'] = encoder1.fit_transform(x['higher'])
x['internet'] = encoder1.fit_transform(x['internet'])
x['romantic'] = encoder1.fit_transform(x['romantic'])

In [19]:
x

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,1,0,0,4,3,4,1,1,3,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,1,1,0,5,3,3,1,1,3,4
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,1,1,0,4,3,2,2,3,3,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,1,1,1,3,2,2,1,1,5,2
4,GP,F,16,U,GT3,T,3,3,other,other,...,1,0,0,4,3,2,1,2,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,1,0,0,5,5,4,4,5,4,11
391,MS,M,17,U,LE3,T,3,1,services,services,...,1,1,0,2,4,5,3,4,2,3
392,MS,M,21,R,GT3,T,1,1,other,other,...,1,0,0,5,5,3,3,3,3,3
393,MS,M,18,R,LE3,T,3,2,services,other,...,1,1,0,4,4,1,3,4,5,0


In [20]:
x = pd.get_dummies(x,dtype = 'int',drop_first= True)
x

,age,Medu,Fedu,traveltime,studytime,failures,schoolsup,famsup,paid,activities,...,Mjob_teacher,Fjob_health,Fjob_other,Fjob_services,Fjob_teacher,reason_home,reason_other,reason_reputation,guardian_mother,guardian_other
0,18,4,4,2,2,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,17,1,1,1,2,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
2,15,1,1,1,2,3,1,0,1,0,...,0,0,1,0,0,0,1,0,1,0
3,15,4,2,1,3,0,0,1,1,1,...,0,0,0,1,0,1,0,0,1,0
4,16,3,3,1,2,0,0,1,1,0,...,0,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,20,2,2,1,2,2,0,1,1,0,...,0,0,0,1,0,0,0,0,0,1
391,17,3,1,2,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
392,21,1,1,1,1,3,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
393,18,3,2,3,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0


In [21]:
x.columns

Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures',
       'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher',
       'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc',
       'health', 'absences', 'school_MS', 'sex_M', 'address_U', 'famsize_LE3',
       'Pstatus_T', 'Mjob_health', 'Mjob_other', 'Mjob_services',
       'Mjob_teacher', 'Fjob_health', 'Fjob_other', 'Fjob_services',
       'Fjob_teacher', 'reason_home', 'reason_other', 'reason_reputation',
       'guardian_mother', 'guardian_other'],
      dtype='object')

In [22]:
x.dtypes

,0
age,int64
Medu,int64
Fedu,int64
traveltime,int64
studytime,int64
failures,int64
schoolsup,int64
famsup,int64
paid,int64
activities,int64


In [23]:
y.head()

,passed
0,0
1,0
2,1
3,1
4,1


# modelling

In [24]:
from  sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(
    x,y,test_size=0.2,random_state =42
)

In [25]:
y.head()

,passed
0,0
1,0
2,1
3,1
4,1


In [26]:
# logistic regression

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
lr_model =LogisticRegression(max_iter=1000)
lr_model.fit(x_train,y_train)
y_pred_lr_model =lr_model.predict(x_test)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [29]:
from sklearn.metrics import confusion_matrix,precision_score
from sklearn.metrics import accuracy_score,f1_score
from sklearn.metrics import recall_score

In [30]:
print(confusion_matrix(y_test,y_pred_lr_model))
print("Accuracy is : " ,accuracy_score(y_test,y_pred_lr_model))
print("Precision is : ",precision_score(y_test,y_pred_lr_model))
print("Recall is : ",recall_score(y_test,y_pred_lr_model))
print("F1 score is : ",f1_score(y_test,y_pred_lr_model))

[[12 15]
 [ 6 46]]
Accuracy is :  0.7341772151898734
Precision is :  0.7540983606557377
Recall is :  0.8846153846153846
F1 score is :  0.8141592920353983


In [31]:
#KNN

In [32]:
# finding the optimum k value
from sklearn.neighbors import KNeighborsClassifier

acc_score =[]
for i in range(3,10):
  knn = KNeighborsClassifier(n_neighbors = i)
  knn.fit(x_train,y_train)
  y_pred_knn = knn.predict(x_test)
  acc = accuracy_score(y_test,y_pred_knn)
  acc_score.append(acc)

/usr/local/lib/python3.13/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.13/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.13/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.13/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for 

In [33]:
acc_score

[0.6455696202531646,
 0.6582278481012658,
 0.6835443037974683,
 0.6455696202531646,
 0.6708860759493671,
 0.6708860759493671,
 0.6708860759493671]

In [34]:
# optimum k value is 5 because accuracy is high when k=5
# train the knn model for k = 5
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(x_train,y_train)
y_pred_knn = knn.predict(x_test)

print(confusion_matrix(y_test,y_pred_knn))
print("Accuracy is : " ,accuracy_score(y_test,y_pred_knn))
print("Precision is : ",precision_score(y_test,y_pred_knn))
print("Recall is : ",recall_score(y_test,y_pred_knn))
print("F1 score is : ",f1_score(y_test,y_pred_knn))

[[ 8 19]
 [ 6 46]]
Accuracy is :  0.6835443037974683
Precision is :  0.7076923076923077
Recall is :  0.8846153846153846
F1 score is :  0.7863247863247863


/usr/local/lib/python3.13/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [35]:
from sklearn.svm import SVC

In [36]:
svm_linear = SVC(kernel = 'linear')
svm_linear.fit(x_train,y_train)
y_pred_svm_linear = svm_linear.predict(x_test)

print(confusion_matrix(y_test,y_pred_svm_linear))
print("Accuracy is : " ,accuracy_score(y_test,y_pred_svm_linear))
print("Precision is : ",precision_score(y_test,y_pred_svm_linear))
print("Recall is : ",recall_score(y_test,y_pred_svm_linear))
print("F1 score is : ",f1_score(y_test,y_pred_svm_linear))

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 9 18]
 [ 7 45]]
Accuracy is :  0.6835443037974683
Precision is :  0.7142857142857143
Recall is :  0.8653846153846154
F1 score is :  0.782608695652174


In [37]:
svm_poly = SVC(kernel = 'poly')
svm_poly.fit(x_train,y_train)
y_pred_svm_poly = svm_poly.predict(x_test)

print(confusion_matrix(y_test,y_pred_svm_poly))
print("Accuracy is : " ,accuracy_score(y_test,y_pred_svm_poly))
print("Precision is : ",precision_score(y_test,y_pred_svm_poly))
print("Recall is : ",recall_score(y_test,y_pred_svm_poly))
print("F1 score is : ",f1_score(y_test,y_pred_svm_poly))

[[ 2 25]
 [ 1 51]]
Accuracy is :  0.6708860759493671
Precision is :  0.6710526315789473
Recall is :  0.9807692307692307
F1 score is :  0.796875


/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [38]:
svm_rbf = SVC(kernel = 'rbf')
svm_rbf.fit(x_train,y_train)
y_pred_svm_rbf = svm_rbf.predict(x_test)

print(confusion_matrix(y_test,y_pred_svm_rbf))
print("Accuracy is : " ,accuracy_score(y_test,y_pred_svm_rbf))
print("Precision is : ",precision_score(y_test,y_pred_svm_rbf))
print("Recall is : ",recall_score(y_test,y_pred_svm_rbf))
print("F1 score is : ",f1_score(y_test,y_pred_svm_rbf))

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 0 27]
 [ 0 52]]
Accuracy is :  0.6582278481012658
Precision is :  0.6582278481012658
Recall is :  1.0
F1 score is :  0.7938931297709924
